# Generated by Django 3.0.9 on 2020-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subheading',
            field=models.TextField(default='Subheading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='Summary', max_length=300),
            preserve_default=False,
        ),
    ]
