# Generated by Django 3.0.9 on 2020-08-03 21:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200803_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
