# Generated by Django 3.0.9 on 2020-08-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200803_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subheading',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
